### ISSUE TITLE
Table stickyHeader has no effect

### ISSUE THREAD

**Issue by dpere326** [oyvindberg/st-material-ui#2]
Thanks for the great work in this library.

Setting `Table.stickyHeader(true)` has no effect in the table heading.

**Comment by oyvindberg** [comment]
Thanks!

I have no idea about this. Verify with [react developer tools](https://beta.reactjs.org/learn/react-developer-tools) that the prop gets through, in that case it would be a bug with this library. Otherwise it's a Material UI bug or wrong usage.
