### ISSUE TITLE
Unable to get event.target.value

### ISSUE THREAD

**Issue by dpere326** [oyvindberg/st-material-ui#3]
I'm having difficulties extracting value from events. Any attempt results in a `java.lang.ClassCastException` where the value can't be cast to String

For example, handling `TablePagination` `onRowsPerPageChange` and accessing the corresponding `event.target.value` results in this issue. 

```
def handleChangeRowsPerPage(event: ReactEventFrom[(HTMLTextAreaElement | HTMLInputElement) & org.scalajs.dom.Element]): Callback = {
  val reducedEvent = event.asInstanceOf[ReactEventFrom[HTMLInputElement]]
  val rpp = reducedEvent.target.value
  rowsPerPage.setState(rpp.toDouble)
}
```

```
TableFooter(
  TableRow(
    TablePagination(
      count = rowCount,
      onPageChange = handleChangePage,
      page = pageNumber.value,
      rowsPerPage = rowsPerPage.value)
      .rowsPerPageOptions(js.Array(25.0, 50.0))
      .onRowsPerPageChange(handleChangeRowsPerPage)
  )
)
```
![Console output](https://user-images.githubusercontent.com/36250293/208999907-11559227-e8cf-48b6-be95-5f3cd442c2b4.png)

Please kindly advise if I'm missing something in the process. 

Thanks!

**Comment by oyvindberg** [comment]
I think this looks like a bug in Material UI, but it's the thing which can easily go unnoticed in Javascript since it won't throw an exception.

`.target.value` for an input or text area field should be a string, but here it is a `number`.

To unblock yourself you can say something like `val rpp = reducedEvent.target.asInstanceOf[js.Dynamic].selectDynamic("value").asInstanceOf[Double]`

**Comment by dpere326** [comment]
Thanks for the quick feedback! The suggested workaround worked like a charm 👍

**Comment by nafg** [comment]
> reducedEvent.target.asInstanceOf[js.Dynamic].selectDynamic("value").asInstanceOf[Double]

No need for `selectDynamic("value")`, the whole point of Dynamic is that you can just do `.value`

So `reducedEvent.target.asInstanceOf[js.Dynamic].value.asInstanceOf[Double]` should work.
